### PR TITLE
feat: handle refresh token and setup format code (#87)

### PR DESCRIPTION
**Pull request by lamxuanthinh**
@Giang-st1-00 @DuyTinh2003  @ImmChad @dung060103  Please review my feat !!!

### CODE REVIEW

**Comment by kennytruong06** [comment]
good ? 👍

**Comment by Duy-Tinh-Dev** [comment]
ok

**Comment by lamxuanthinh** [comment]
@Giang-st1-00 @dung060103   Please review my feat

**Comment by Giang-st1-00** [comment]
!ok

**Pull request merged**
