### PR TITLE
DT-64 <fix: update ui pricing plans>

### PR DESCRIPTION
**Pull request by Duy-Tinh-Dev**
update ui pricing plans

### CODE REVIEW

**Comment by lamxuanthinh** [comment]
@Giang-st1-00 ?

**Comment by lamxuanthinh** [comment]
@DuyTinh2003  Please write description pull request

**Comment by lamxuanthinh** [comment]
Screenshot 2023-09-18 at 22 57 22
Please change the router of `pricingplans` @DuyTinh2003

**Comment by Giang-st1-00** [comment]
ok

**Pull request merged**
