### PR TITLE
update: input animation (#64)

### PR DESCRIPTION
**Pull request by Duy-Tinh-Dev**

### CODE REVIEW

**Comment by lamxuanthinh** [comment]
Screenshot 2023-06-10 at 14 00 29


this is not good

**Comment by lamxuanthinh** [comment]
Screenshot 2023-06-10 at 14 03 45


I find one problem

**Comment by lamxuanthinh** [comment]
Screenshot 2023-06-10 at 14 44 27

hehe, please fix

**Comment by kennytruong06** [comment]
In my opinion, About the code is no problem. But about templates which not same as the design ?? 
image

**Comment by Duy-Tinh-Dev** [comment]
@ImmChad if i code the same template it has many animation must code. In my code i reuse animation so it not the same template.I think animation it also oke. if you want i will code the same template.

**Pull request merged**
