### PR TITLE
feat: edit video ui navbar (#72)

### PR DESCRIPTION
**Pull request by Duy-Tinh-Dev**

### CODE REVIEW

**Comment by Duy-Tinh-Dev** [comment]
@lamxuanthinh  please check and merge

**Comment by lamxuanthinh** [comment]
@Giang-st1-00 @ImmChad  Please check the pull request by @DuyTinh2003

**Comment by Giang-st1-00** [comment]
ok

**Comment by kennytruong06** [comment]
image
 This is feature or error ?

**Comment by kennytruong06** [comment]
Excellent, you have a good brain. 
image

**Comment by Duy-Tinh-Dev** [comment]
> image This is feature or error ?
@ImmChad 
you are saying error has two navigation, if it . it is not error

**Comment by kennytruong06** [comment]
> > image This is feature or error ?
> > @ImmChad
> > you are saying error has two navigation, if it . it is not error

Oki so that's no problem

**Comment by kennytruong06** [comment]
@DuyTinh2003  oki

**Pull request merged**
