### PR TITLE
fix: format code profile (#112)

### PR DESCRIPTION
**Pull request by kennytruong06**

### CODE REVIEW

**Comment by DuyTinh2003** [comment]
ok

**Comment by lamxuanthinh** [comment]
@Giang-st1-00 @DuyTinh2003  Please review this code

**Comment by Duy-Tinh-Dev** [comment]
ok

**Comment by lamxuanthinh** [comment]
@Giang-st1-00

**Comment by lamxuanthinh** [comment]
@Giang-st1-00  Please review this code

**Comment by lamxuanthinh** [comment]
@ImmChad  oke Please confirm I will merge  !!!

**Comment by Giang-st1-00** [comment]
ok

**Pull request merged**
