### PR TITLE
fix: format code (#111)

### PR DESCRIPTION
**Pull request by Duy-Tinh-Dev**

### CODE REVIEW

**Comment by Duy-Tinh-Dev** [comment]
@Giang-st1-00 , @ImmChad  review my code ✌️.

**Comment by kennytruong06** [comment]
good 👍

**Comment by Giang-st1-00** [comment]
I think change name commit "fix" to "refactor"

**Comment by Giang-st1-00** [comment]
when I click to button play "in video" then control bar is inactive
https://github.com/lamxuanthinh/DGU/assets/91960480/5f717e1d-8804-43e8-891d-0220e100f4d0

**Comment by Giang-st1-00** [comment]
button play pause asynchronous
image

**Comment by Giang-st1-00** [comment]
and when i refresh web then ...
image

**Comment by Giang-st1-00** [comment]
image
delete comment and import not use

**Comment by Giang-st1-00** [comment]
image
modal in Views ??? .I think move to common in component and change name to "abc.....Modal"

**Pull request merged**
