### PR TITLE
update UI HomePage (#86)

### PR DESCRIPTION
**Pull request by kennytruong06**
@Giang-st1-00  @DuyTinh2003  review code

### CODE REVIEW

**Review by Duy-Tinh-Dev — COMMENTED** [review]
code no problem.

**Comment by lamxuanthinh** [comment]
@Giang-st1-00  Please reivew

**Comment by Giang-st1-00** [comment]
image
image
the space is not equal

**Comment by Duy-Tinh-Dev** [comment]
image
i think the home icon not beautiful Can you change it

**Comment by Duy-Tinh-Dev** [comment]
image
image
i think need has "cursor pointer" when user hover  to Logo, icon bell and message

**Comment by kennytruong06** [comment]
> image image i think need has "cursor pointer" when user hover to Logo, icon bell and message

Done!

**Comment by kennytruong06** [comment]
> image image the space is not equal

Done!

**Comment by kennytruong06** [comment]
@lamxuanthinh  all say "oki" so you merge now

**Comment by lamxuanthinh** [comment]
oki

**Pull request merged**
